### ISSUE TITLE
Optifine兼容性问题

### ISSUE THREAD

**Issue by senseab** [cthbleachbit/TransitRailMod#2]
门玻璃显示不正常

**Comment by cthbleachbit** [comment]
在 commit 23e10fc 中，使用 Optifine HD Ultra H6 测试已无渲染异常，原因不明，将会抽取 commit 进行测试寻找原因
![2016-06-22_17 57 03](https://cloud.githubusercontent.com/assets/3353318/16292875/f7788466-3947-11e6-8410-a88471469d84.png)
