### ISSUE TITLE
想要有（上下左右）拐弯的电缆架

### ISSUE THREAD

**Issue by Lwrless** [cthbleachbit/TransitRailMod#3]

**Comment by cthbleachbit** [comment]
都没有进一步的 description，网绿你没诚意啊

**Comment by Lwrless** [comment]
毕竟一句话就能明白的事情...

**Comment by cthbleachbit** [comment]
orz 我想用更没诚意的方法解决……以下两个方案
1. 新的方块：一个转弯的电缆架，`meta` 中用 2 bit 指示放置者朝向，2 bit 指示左转右转，上升和下降
2. 新的方块：电缆架末端，直接做成半个铁块把电缆啥的遮住，假装在转弯

**Comment by Lwrless** [comment]
...谜之假装在拐弯，感觉 1 很好啊。

**Comment by cthbleachbit** [comment]
方块逻辑于 commit a539368 中完成，准备添加模型。

**Comment by cthbleachbit** [comment]
现在凑合随便拿了个模型……可以把 F3 按出来查看 `BlockState`

**Comment by cthbleachbit** [comment]
然而上升下降还是做不出来，2 就拿来替代上升下降的部分了

**Comment by cthbleachbit** [comment]
commit a41fca7 增加了正确的模型

**Comment by cthbleachbit** [comment]
1 已经在 commit 24813f4 中完全实现。

**Comment by cthbleachbit** [comment]
Fully implemented. Closing.
